name: CD

on:
  push:
    tags:
      - "v*.*.*"

env:
  target: x86_64-unknown-linux-musl

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install musl
        run: sudo apt-get update && sudo apt-get install -y musl musl-tools
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ env.target }}
          default: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ env.target }}
      - name: Strip binary
        run: strip ./target/${{ env.target }}/release/container-stats
      - name: Move binary
        run: mv target/${{ env.target }}/release/container-stats container-stats-${{ env.target }}
      - name: Upload binary
        uses: softprops/action-gh-release@v1
        with:
          files: |
            container-stats-${{ env.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
